//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InitialProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InitialProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation info.
        /// </summary>
        public static string AccommodationInfo {
            get {
                return ResourceManager.GetString("AccommodationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation.
        /// </summary>
        public static string Accommodations {
            get {
                return ResourceManager.GetString("Accommodations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anytime/anywhere.
        /// </summary>
        public static string AnytimeAnywhere {
            get {
                return ResourceManager.GetString("AnytimeAnywhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartment.
        /// </summary>
        public static string Apartment {
            get {
                return ResourceManager.GetString("Apartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available accommodations.
        /// </summary>
        public static string AvailableAccommodations {
            get {
                return ResourceManager.GetString("AvailableAccommodations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available dates.
        /// </summary>
        public static string AvailableDates {
            get {
                return ResourceManager.GetString("AvailableDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus points:.
        /// </summary>
        public static string BonusPoints {
            get {
                return ResourceManager.GetString("BonusPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        public static string Book {
            get {
                return ResourceManager.GetString("Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel reservation.
        /// </summary>
        public static string CancelReservation {
            get {
                return ResourceManager.GetString("CancelReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change dates.
        /// </summary>
        public static string ChangeDates {
            get {
                return ResourceManager.GetString("ChangeDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City:.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string CityDG {
            get {
                return ResourceManager.GetString("CityDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleanliness:.
        /// </summary>
        public static string Cleanliness {
            get {
                return ResourceManager.GetString("Cleanliness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment:.
        /// </summary>
        public static string CommentDD {
            get {
                return ResourceManager.GetString("CommentDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password:.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correctness:.
        /// </summary>
        public static string Correctness {
            get {
                return ResourceManager.GetString("Correctness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cottage.
        /// </summary>
        public static string Cottage {
            get {
                return ResourceManager.GetString("Cottage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country:.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string CountryDG {
            get {
                return ResourceManager.GetString("CountryDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new thread.
        /// </summary>
        public static string CreateNewThread {
            get {
                return ResourceManager.GetString("CreateNewThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current dates.
        /// </summary>
        public static string CurrentDates {
            get {
                return ResourceManager.GetString("CurrentDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current dates:.
        /// </summary>
        public static string CurrentDatesDD {
            get {
                return ResourceManager.GetString("CurrentDatesDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark theme.
        /// </summary>
        public static string DarkTheme {
            get {
                return ResourceManager.GetString("DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date change requests.
        /// </summary>
        public static string DateChaneRequests {
            get {
                return ResourceManager.GetString("DateChaneRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date change.
        /// </summary>
        public static string DateChange {
            get {
                return ResourceManager.GetString("DateChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        public static string DateDD {
            get {
                return ResourceManager.GetString("DateDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration of stay:.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find available dates.
        /// </summary>
        public static string FindAvailableDates {
            get {
                return ResourceManager.GetString("FindAvailableDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following the rules:.
        /// </summary>
        public static string FollowingTheRules {
            get {
                return ResourceManager.GetString("FollowingTheRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum.
        /// </summary>
        public static string Forum {
            get {
                return ResourceManager.GetString("Forum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate a report.
        /// </summary>
        public static string GenerateAReport {
            get {
                return ResourceManager.GetString("GenerateAReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate your report.
        /// </summary>
        public static string GenerateYourReport {
            get {
                return ResourceManager.GetString("GenerateYourReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of guests:.
        /// </summary>
        public static string GuestNumber {
            get {
                return ResourceManager.GetString("GuestNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House.
        /// </summary>
        public static string House {
            get {
                return ResourceManager.GetString("House", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string ImagePreview {
            get {
                return ResourceManager.GetString("ImagePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images:.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level of urgency:.
        /// </summary>
        public static string LevelOfUrgency {
            get {
                return ResourceManager.GetString("LevelOfUrgency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make reservation.
        /// </summary>
        public static string MakeReservation {
            get {
                return ResourceManager.GetString("MakeReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max guests.
        /// </summary>
        public static string MaxGuests {
            get {
                return ResourceManager.GetString("MaxGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min days before cancel.
        /// </summary>
        public static string MinDaysBeforeCancel {
            get {
                return ResourceManager.GetString("MinDaysBeforeCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min reservations days.
        /// </summary>
        public static string MinReservationDays {
            get {
                return ResourceManager.GetString("MinReservationDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameDG {
            get {
                return ResourceManager.GetString("NameDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password:.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post a comment.
        /// </summary>
        public static string PostAComment {
            get {
                return ResourceManager.GetString("PostAComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question:.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate your stay.
        /// </summary>
        public static string RateYourStay {
            get {
                return ResourceManager.GetString("RateYourStay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request a date change.
        /// </summary>
        public static string RequestADateChange {
            get {
                return ResourceManager.GetString("RequestADateChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested dates:.
        /// </summary>
        public static string RequestedDatesDD {
            get {
                return ResourceManager.GetString("RequestedDatesDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservations.
        /// </summary>
        public static string Reservations {
            get {
                return ResourceManager.GetString("Reservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve.
        /// </summary>
        public static string Reserve {
            get {
                return ResourceManager.GetString("Reserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        public static string Reviews {
            get {
                return ResourceManager.GetString("Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled.
        /// </summary>
        public static string Scheduled {
            get {
                return ResourceManager.GetString("Scheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbian.
        /// </summary>
        public static string Serbian {
            get {
                return ResourceManager.GetString("Serbian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status of reservation:.
        /// </summary>
        public static string StatusOfReservation {
            get {
                return ResourceManager.GetString("StatusOfReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit your review.
        /// </summary>
        public static string SubmitYourReview {
            get {
                return ResourceManager.GetString("SubmitYourReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggest a renovation.
        /// </summary>
        public static string SuggestRenovation {
            get {
                return ResourceManager.GetString("SuggestRenovation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string TypeDG {
            get {
                return ResourceManager.GetString("TypeDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all requests.
        /// </summary>
        public static string ViewAllRequests {
            get {
                return ResourceManager.GetString("ViewAllRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was user there?.
        /// </summary>
        public static string WasUserThere {
            get {
                return ResourceManager.GetString("WasUserThere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What should be renovated:.
        /// </summary>
        public static string WhatShouldBeRenovated {
            get {
                return ResourceManager.GetString("WhatShouldBeRenovated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your comment:.
        /// </summary>
        public static string YourComment {
            get {
                return ResourceManager.GetString("YourComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile.
        /// </summary>
        public static string YourProfile {
            get {
                return ResourceManager.GetString("YourProfile", resourceCulture);
            }
        }
    }
}
